ExerciseRoutine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import hello, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'account'

urlpatterns = [
    path('hello/', hello, name='hello'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

account/models.py
from django.db import models

# Create your models here.

class SampleModel(models.Model):
    text = models.CharField(max_length=255)

account/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 수정 시 아이디 불가하게 하기 위함.
        self.fields['username'].disabled = True

account/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from account.decorators import account_ownership_required
from account.forms import AccountUpdateForm
from account.models import SampleModel

is_ownership = [account_ownership_required, login_required]


@login_required
def hello(request):
    if request.method == "POST":
        temp = request.POST.get('helloworldinput')
        new_model = SampleModel()
        new_model.text = temp
        new_model.save()

        return HttpResponseRedirect(reverse('account:hello'))
    else:
        hello_world_list = SampleModel.objects.all()
        return render(request, 'accountapp/helloword.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('account:hello')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(is_ownership, 'get')
@method_decorator(is_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('account:hello')
    template_name = 'accountapp/update.html'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super().get(*args, **kwargs)


@method_decorator(is_ownership, 'get')
@method_decorator(is_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('account:login')
    template_name = 'accountapp/delete.html'

account/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'account:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
        </form>
    </div>

{% endblock %}

account/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url 'account:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

account/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" alt=""
                     style="height: 10rem; width:10rem; border-radius: 10rem; margin-bottom: 2rem">
                <h2 style="font-family: 'NanumSquareRoundBN'">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            edit
                        </a>
                    {% endif %}
                    <h5 style="margin-bottom:2rem">
                        {{ target_user.profile.message }}
                    </h5>
                </h2>
            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h2 style="font-family: 'NanumSquareRoundBN'">
                            Create Profile
                        </h2>
                    </a>
                {% else %}
                    <h2>
                    닉네임이 없는 사람
                    </h2>
                {% endif %}
            {% endif %}
            {% if target_user == user %}
                <a href="{% url 'account:update' pk=user.pk %}">
                    <p>
                        Change Info
                    </p>
                </a>
                <a href="{% url 'account:delete' pk=user.pk %}">
                    <p>
                        Quit
                    </p>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

account/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="", method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
            </form>
        </div>
    </div>
{% endblock %}

account/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action="{% url 'account:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
        </form>
    </div>

{% endblock %}