ExerciseRoutine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import hello, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'account'

urlpatterns = [
    path('hello/', hello, name='hello'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body style="font-family: NanumSquareRoundR">

    {% include 'header.html' %}

    <hr>

    {% block content %}

    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <<div style="text-align:center; margin-top: 1rem;">
        <div class="basic_footer_button">
            <span>공지사항</span> |
            <span>원량</span> |
            <span>운동루틴등록</span> |
            <span>등등</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="basic_footer_logo">Do Exercise</h6>
        </div>
    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ExerciseRoutine</title>
    {#boot strap#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {#    GOOGLE FONTS   #}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face{
            font-family: 'NanumSquareRoundB';
            src: local('NanumSquareRoundB'),
            url("{% static 'fonts/NanumSquareRoundB.ttf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundEB';
            src: local('NanumSquareRoundEB'),
            url("{% static 'fonts/NanumSquareRoundEB.ttf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundL';
            src: local('NanumSquareRoundL'),
            url("{% static 'fonts/NanumSquareRoundL.ttf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundR';
            src: local('NanumSquareRoundR'),
            url("{% static 'fonts/NanumSquareRoundR.ttf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
    <div style="text-align:center; margin: 2rem 0;">
        <div>
            <h1 style="font-family: 'Montserrat', sans-serif;">Do Exercise</h1>
        </div>
        <div class="nav_header_nav_bar">
            <a href="{% url 'articleapp:list' %}?next={{ request.path }}" class="nav_header">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="nav_header">
                <span>Projects</span>
            </a>
            {% if not user.is_authenticated %}
            <a href="{% url 'account:login' %}?next={{ request.path }}" class="nav_header">
                <span>login</span>
            </a>
            <a href="{% url 'account:create' %}?next={{ request.path }}" class="nav_header">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'account:detail' pk=user.pk %}" class="nav_header">
                <span>MyPage</span>
            </a>
            <a href="{% url 'account:logout'%}?next={{ request.path }}" class="nav_header">
                <span>logout</span>
            </a>
            {% endif%}
        </div>
    </div>